services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    container_name: test_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
